### ISSUE TITLE
Clear display mode "subdisplay" state when toggling display modes

### ISSUE THREAD

**Issue by jacobwegner** [scaife-viewer/frontend#26]

**Comment by paltman** [comment]
@jacobwegner what do you mean by "subdisplay" state?

**Comment by jacobwegner** [comment]
@paltman: I think of subdisplay state as things that are only accessible within a certain display mode (like choosing to see only folio or choosing to see maps side by side with the text, selecting an alignment, etc).

A quick check shows we seem to be clearing those things correctly (because most of that state is tied to the "active" display mode component), but I'll make a note in #25 to make sure we "clear" things correctly in a "querystring" world too.

(We wrote a few handlers in Digital Sira on component `destroy` I think to help with this)
