### ISSUE TITLE
Make title tag more descriptive

### ISSUE THREAD

**Issue by jacobwegner** [scaife-viewer/frontend#28]
@jtauber wrote:
> we need to go through and add <title> elements in Scaife
> everything is just “skeleton” at the moment

**Comment by jacobwegner** [comment]
@jtauber ready for review at: https://deploy-preview-46--sv-mini.netlify.app/reader?urn=urn%3Acts%3AgreekLit%3Atlg0012.tlg001.perseus-grc2%3A1.1-1.7

**Comment by jtauber** [comment]
I'm wondering if this should include the passage reference too (although it's certainly a lot better now than it was).
