### ISSUE TITLE
Defining default colors for links

### ISSUE THREAD

**Issue by jacobwegner** [scaife-viewer/frontend#3]
@paltman: I've been experimenting with the frontend "demo" packages as part of [](https://github.com/scaife-viewer/sv-mini-atlas/issues/13) and noticed that the "demo mode" here falls back to the browser defaults for link colors:

![image](https://user-images.githubusercontent.com/629062/90068293-08526e80-dcb6-11ea-9cf9-f170dae3a17c.png)

vs Explore Homer:

![image](https://user-images.githubusercontent.com/629062/90068266-fd97d980-dcb5-11ea-8ba2-d81367edab58.png)

https://github.com/scaife-viewer/explorehomer/blob/3f50dcc83a2a968059719b7fb2cb05069e5aef7d/src/App.vue#L47

I'd suggest we take that into consideration as part of using "theming" using these packages in [scaife-viewer/explorehomer](https://github.com/scaife-viewer/explorehomer).

There are places (in the siblings widget and library) using the browser colors  and other places (the folio images mode) where we've defined the default as the "accent" color used in EH.

**Comment by paltman** [comment]
Thanks for creating the issue. Thus a few other bits have slipped through now that we don’t have global styles defined in EH that are top of mind to get back to on a “detail” pass. 

>
